version: "3"

services:
  nginx:
    restart: always
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      - app2
    networks:
      - gpt

  app1:
    restart: always
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080
    networks:
      - gpt

  app2:
    restart: always
    image: si3mshady/awsthree:4
    ports:
      - 3000
    networks:
      - gpt

networks:
  gpt:
    driver: bridge
